version: "3.3"
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    env_file:
      - env.list
    volumes:
      - ./mqtt-to-kafka/zookeeper/data:/data
      - ./mqtt-to-kafka/zookeeper/datalog:/datalog
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - env.list
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mosquitto:
    build: ./mosquitto_broker
    container_name: mosquitto
    volumes:
      #- ./kafka-mqtt-connect/config/:/mosquitto/config/:rw
      - ./mqtt-to-kafka/log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - "1883:1883"
  mqtt-to-kafka:
    build: ./mqtt-to-kafka
    container_name: mqtt-to-kafka
    depends_on:
      - kafka
      - mosquitto
    volumes:
      - ./mqtt-to-kafka:/mqtt-to-kafka
    command: python /mqtt-to-kafka/mqtt_to_kafka.py
  spark-streaming:
    build: ./spark-streaming
    container_name: spark-streaming
    depends_on:
      - kafka
      - mqtt-to-kafka
    volumes:
      - ./spark-streaming:/spark-streaming
    command: spark-submit --master local[*] /app/streaming.py
volumes:
  data: ~
