version: "3.3"
services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    env_file:
      - env.list
    volumes:
      - ./kafka-mqtt-connect/zookeeper/data:/data
      - ./kafka-mqtt-connect/zookeeper/datalog:/datalog
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9095:9092"
    env_file:
      - env.list
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mosquitto:
    build: ./mosquitto_broker
    container_name: mosquitto
    volumes:
      #- ./kafka-mqtt-connect/config/:/mosquitto/config/:rw
      - ./kafka-mqtt-connect/log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - "1883:1883"
  mqtt-to-kafka:
    build: ./kafka-mqtt-connect
    container_name: mqtt-to-kafka
    depends_on:
      - kafka
      - mosquitto
  prediction:
    build: ./prediction-code
    container_name: prediction
    depends_on:
      - mosquitto
    volumes:
      - ./prediction-code:/prediction-code
    command: python /prediction-code/prediction.py 
volumes:
  data: ~
